
//! Autogenerated weights for pallet_trustless_file_server
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-14, STEPS: `50`, REPEAT: `100`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Joses-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/node-template
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_trustless_file_server
// --execution=wasm
// --wasm-execution=compiled
// --extrinsic
// *
// --steps
// 50
// --repeat
// 100
// --output
// weights.rs
// --template
// ./.maintain/frame-weight-template.hbs
// --heap-pages
// 4096

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_trustless_file_server.
pub trait WeightInfo {
	fn upload_file(x: u32, ) -> Weight;
}

/// Weights for pallet_trustless_file_server using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: TrustlessFileServer Files (r:0 w:1)
	/// Proof: TrustlessFileServer Files (max_values: None, max_size: Some(150), added: 2625, mode: MaxEncodedLen)
	/// The range of component `x` is `[1024, 32768]`.
	fn upload_file(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(14_013_003, 0)
			// Standard Error: 6
			.saturating_add(Weight::from_parts(3_825, 0).saturating_mul(x.into()))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: TrustlessFileServer Files (r:0 w:1)
	/// Proof: TrustlessFileServer Files (max_values: None, max_size: Some(150), added: 2625, mode: MaxEncodedLen)
	/// The range of component `x` is `[1024, 32768]`.
	fn upload_file(x: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(14_013_003, 0)
			// Standard Error: 6
			.saturating_add(Weight::from_parts(3_825, 0).saturating_mul(x.into()))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
